apiVersion: v1
kind: Service
metadata:
  name: argocd-webui
  namespace: argocd
spec:
  ports:
  - nodePort: 31188
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
