apiVersion: v1
kind: Service
metadata:
  name: argocd-webui
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
